[package]
name = "competitive-lib"
version = "0.1.0"
authors = ["zero-sharp"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "*"

[dev-dependencies]
cli_test_dir = "0.1"
